[package]
name = "rocket-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
diesel = { version = "2.2.0", features = ["mysql", "r2d2"] }
dotenvy = "0.15"
diesel-async = { version = "0.5.0", features = ["mysql", "tokio"] }
tokio = { version = "1.0", features = ["full"] }