[default]
address = "0.0.0.0"
limits = { form = "128 kB", json = "2 MiB" }
workers = 16
max_blocking = 512
keep_alive = 5
cli_colors = true

[debug]
port = 8888
workers = 8

[nyc]
port = 8001
workers = 10

[release]
port = 9999
workers = 16