name: Run tests for rocket auth
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true

      - name: Install dependencies and build
        run: cargo build --verbose

      - name: Run Utils tests
        run: cargo test utils

      - name: Database setup
        run: |
          docker compose -f ./src/test/docker-compose.yaml up -d
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/diesel-rs/diesel/releases/latest/download/diesel_cli-installer.sh | sh
          source ./env-test.sh
          sleep 10
          diesel migration run

      - name: Run Integration tests
        run: |
          source ./env-test.sh
          cargo test integration

      - name: Run Controller tests
        run: |
          source ./env-test.sh
          cargo test controllers
